# -*- coding: utf-8 -*-
"""AAI LAb 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvNlEWPtUgSsAELx9XLTdBztfDnNxIT6
"""

!pip install groq requests pandas

"""
Stock Market SaaS - Single Agent
---------------------------------
A single-agent system that answers questions about stocks by calling tools:
  - get_stock_data      -> historical OHLCV (cached in SQLite)
  - get_live_price       -> latest quote (60s cache)
  - get_indicators       -> RSI + SMA20 computed from cached history
  - predict_next          -> simple linear regression on recent closes
  - suggest_action        -> rule-based BUY/HOLD/SELL score

Requirements:
    pip install requests groq pandas

"""

import os
import json
import sqlite3
import requests
import pandas as pd
from datetime import datetime, timedelta
from groq import Groq

# ----------------------------------------------------------------------------
# Config
# ----------------------------------------------------------------------------

ALPHA_VANTAGE_API_KEY = os.environ.get("ALPHA_VANTAGE_API_KEY", "")
BASE_URL = "https://www.alphavantage.co/query"
DB_PATH = "stocks.db"
LIVE_PRICE_CACHE_TTL = 60          # seconds
HISTORY_CACHE_TTL = 60 * 60 * 6    # 6 hours - daily data doesn't change often

client = Groq()  # reads GROQ_API_KEY from env automatically
MODEL = "openai/gpt-oss-20b"  # fast, tool-calling capable, available on developer tier


# ----------------------------------------------------------------------------
# Database setup
# ----------------------------------------------------------------------------

def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS ohlcv (
            symbol TEXT,
            date TEXT,
            open REAL,
            high REAL,
            low REAL,
            close REAL,
            volume INTEGER,
            PRIMARY KEY (symbol, date)
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS live_price_cache (
            symbol TEXT PRIMARY KEY,
            price REAL,
            change_pct TEXT,
            fetched_at TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS history_meta (
            symbol TEXT PRIMARY KEY,
            fetched_at TEXT
        )
    """)
    conn.commit()
    conn.close()


# ----------------------------------------------------------------------------
# Tool 1: Historical OHLCV data (cache-or-fetch)
# ----------------------------------------------------------------------------

def get_stock_data(symbol: str, days: int = 30) -> dict:
    """Return the last `days` of daily OHLCV for a symbol, using SQLite cache."""
    symbol = symbol.upper()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    meta = conn.execute(
        "SELECT fetched_at FROM history_meta WHERE symbol = ?", (symbol,)
    ).fetchone()

    is_stale = True
    if meta:
        fetched_at = datetime.fromisoformat(meta["fetched_at"])
        is_stale = datetime.now() - fetched_at > timedelta(seconds=HISTORY_CACHE_TTL)

    if is_stale:
        try:
            resp = requests.get(BASE_URL, params={
                "function": "TIME_SERIES_DAILY",
                "symbol": symbol,
                "outputsize": "compact",  # last ~100 days
                "apikey": ALPHA_VANTAGE_API_KEY
            }, timeout=10)
            resp.raise_for_status()
            payload = resp.json()
            series = payload.get("Time Series (Daily)")

            if not series:
                conn.close()
                return {"symbol": symbol, "error": "No historical data returned — check symbol or rate limit"}

            rows = []
            for date_str, values in series.items():
                rows.append((
                    symbol, date_str,
                    float(values["1. open"]), float(values["2. high"]),
                    float(values["3. low"]), float(values["4. close"]),
                    int(values["5. volume"])
                ))

            conn.executemany("""
                INSERT INTO ohlcv (symbol, date, open, high, low, close, volume)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(symbol, date) DO UPDATE SET
                    open=excluded.open, high=excluded.high, low=excluded.low,
                    close=excluded.close, volume=excluded.volume
            """, rows)

            conn.execute("""
                INSERT INTO history_meta (symbol, fetched_at) VALUES (?, ?)
                ON CONFLICT(symbol) DO UPDATE SET fetched_at=excluded.fetched_at
            """, (symbol, datetime.now().isoformat()))
            conn.commit()

        except requests.RequestException as e:
            conn.close()
            return {"symbol": symbol, "error": f"API call failed: {str(e)}"}

    df = pd.read_sql_query(
        "SELECT * FROM ohlcv WHERE symbol = ? ORDER BY date DESC LIMIT ?",
        conn, params=(symbol, days)
    )
    conn.close()

    if df.empty:
        return {"symbol": symbol, "error": "No data available for this symbol"}

    df = df.sort_values("date")
    return {
        "symbol": symbol,
        "rows": df.to_dict(orient="records"),
        "count": len(df)
    }


# ----------------------------------------------------------------------------
# Tool 2: Live price (cache-or-fetch, short TTL)
# ----------------------------------------------------------------------------

def get_live_price(symbol: str) -> dict:
    """Return the latest quote for a symbol, cached for LIVE_PRICE_CACHE_TTL seconds."""
    symbol = symbol.upper()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    row = conn.execute(
        "SELECT * FROM live_price_cache WHERE symbol = ?", (symbol,)
    ).fetchone()

    if row:
        fetched_at = datetime.fromisoformat(row["fetched_at"])
        if datetime.now() - fetched_at < timedelta(seconds=LIVE_PRICE_CACHE_TTL):
            conn.close()
            return {
                "symbol": symbol, "price": row["price"],
                "change_pct": row["change_pct"], "source": "cache"
            }

    try:
        resp = requests.get(BASE_URL, params={
            "function": "GLOBAL_QUOTE",
            "symbol": symbol,
            "apikey": ALPHA_VANTAGE_API_KEY
        }, timeout=10)
        resp.raise_for_status()
        data = resp.json().get("Global Quote", {})

        if not data or "05. price" not in data:
            conn.close()
            return {"symbol": symbol, "error": "No data returned — check symbol or rate limit"}

        price = float(data["05. price"])
        change_pct = data.get("10. change percent", "N/A")

        conn.execute("""
            INSERT INTO live_price_cache (symbol, price, change_pct, fetched_at)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(symbol) DO UPDATE SET
                price=excluded.price, change_pct=excluded.change_pct, fetched_at=excluded.fetched_at
        """, (symbol, price, change_pct, datetime.now().isoformat()))
        conn.commit()
        conn.close()
        return {"symbol": symbol, "price": price, "change_pct": change_pct, "source": "live"}

    except requests.RequestException as e:
        conn.close()
        return {"symbol": symbol, "error": f"API call failed: {str(e)}"}


# ----------------------------------------------------------------------------
# Tool 3: Indicators (RSI + SMA20), computed from cached history
# ----------------------------------------------------------------------------

def get_indicators(symbol: str) -> dict:
    """Compute RSI(14) and SMA(20) from the cached historical close prices."""
    data = get_stock_data(symbol, days=60)
    if "error" in data:
        return data

    df = pd.DataFrame(data["rows"])
    if len(df) < 20:
        return {"symbol": symbol, "error": "Not enough history to compute indicators"}

    closes = df["close"]

    # SMA20
    sma20 = closes.rolling(window=20).mean().iloc[-1]

    # RSI14 (manual, no extra dependency)
    delta = closes.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=14).mean().iloc[-1]
    avg_loss = loss.rolling(window=14).mean().iloc[-1]
    rs = avg_gain / avg_loss if avg_loss != 0 else float("inf")
    rsi = 100 - (100 / (1 + rs))

    return {
        "symbol": symbol,
        "close": round(float(closes.iloc[-1]), 2),
        "sma_20": round(float(sma20), 2),
        "rsi_14": round(float(rsi), 2)
    }


# ----------------------------------------------------------------------------
# Tool 4: Prediction (simple linear regression on recent closes)
# ----------------------------------------------------------------------------

def predict_next(symbol: str) -> dict:
    """Fit a quick linear regression on the last 20 closes to predict the next one."""
    data = get_stock_data(symbol, days=20)
    if "error" in data:
        return data

    df = pd.DataFrame(data["rows"]).sort_values("date")
    if len(df) < 10:
        return {"symbol": symbol, "error": "Not enough history to predict"}

    closes = df["close"].values
    x = list(range(len(closes)))

    # Manual least-squares fit (avoids sklearn dependency)
    n = len(x)
    mean_x = sum(x) / n
    mean_y = sum(closes) / n
    numerator = sum((x[i] - mean_x) * (closes[i] - mean_y) for i in range(n))
    denominator = sum((x[i] - mean_x) ** 2 for i in range(n))
    slope = numerator / denominator if denominator != 0 else 0
    intercept = mean_y - slope * mean_x

    next_x = n
    predicted_close = slope * next_x + intercept
    direction = "up" if predicted_close > closes[-1] else "down"

    return {
        "symbol": symbol,
        "last_close": round(float(closes[-1]), 2),
        "predicted_next_close": round(float(predicted_close), 2),
        "direction": direction
    }


# ----------------------------------------------------------------------------
# Tool 5: Suggestion (rule-based, deterministic)
# ----------------------------------------------------------------------------

def suggest_action(symbol: str) -> dict:
    """Combine indicators + prediction into a simple BUY/HOLD/SELL score."""
    indicators = get_indicators(symbol)
    prediction = predict_next(symbol)

    if "error" in indicators:
        return indicators
    if "error" in prediction:
        return prediction

    score = 0
    reasons = []

    if indicators["rsi_14"] < 30:
        score += 1
        reasons.append("RSI indicates oversold conditions")
    elif indicators["rsi_14"] > 70:
        score -= 1
        reasons.append("RSI indicates overbought conditions")

    if indicators["close"] > indicators["sma_20"]:
        score += 1
        reasons.append("price is above the 20-day moving average")
    else:
        score -= 1
        reasons.append("price is below the 20-day moving average")

    if prediction["direction"] == "up":
        score += 1
        reasons.append("short-term model predicts an upward move")
    else:
        score -= 1
        reasons.append("short-term model predicts a downward move")

    if score >= 2:
        action = "BUY"
    elif score <= -2:
        action = "SELL"
    else:
        action = "HOLD"

    return {
        "symbol": symbol,
        "action": action,
        "score": score,
        "reasons": reasons,
        "disclaimer": "Not financial advice — based on limited historical data and simple heuristics."
    }


# ----------------------------------------------------------------------------
# Tool dispatch table
# ----------------------------------------------------------------------------

TOOL_FUNCTIONS = {
    "get_stock_data": get_stock_data,
    "get_live_price": get_live_price,
    "get_indicators": get_indicators,
    "predict_next": predict_next,
    "suggest_action": suggest_action,
}

TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "get_stock_data",
            "description": "Get recent historical daily OHLCV data for a stock symbol.",
            "parameters": {
                "type": "object",
                "properties": {
                    "symbol": {"type": "string", "description": "Stock ticker, e.g. AAPL"},
                    "days": {"type": "integer", "description": "Number of recent days to return (default 30)"}
                },
                "required": ["symbol"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_live_price",
            "description": "Get the latest quote (price + % change) for a stock symbol.",
            "parameters": {
                "type": "object",
                "properties": {"symbol": {"type": "string", "description": "Stock ticker, e.g. AAPL"}},
                "required": ["symbol"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_indicators",
            "description": "Get RSI(14) and SMA(20) technical indicators for a stock symbol.",
            "parameters": {
                "type": "object",
                "properties": {"symbol": {"type": "string", "description": "Stock ticker, e.g. AAPL"}},
                "required": ["symbol"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "predict_next",
            "description": "Predict the next day's closing price using a simple linear regression on recent closes.",
            "parameters": {
                "type": "object",
                "properties": {"symbol": {"type": "string", "description": "Stock ticker, e.g. AAPL"}},
                "required": ["symbol"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "suggest_action",
            "description": "Get a rule-based BUY/HOLD/SELL suggestion for a stock symbol, combining indicators and prediction.",
            "parameters": {
                "type": "object",
                "properties": {"symbol": {"type": "string", "description": "Stock ticker, e.g. AAPL"}},
                "required": ["symbol"]
            }
        }
    },
]

SYSTEM_PROMPT = """You are a stock market assistant. You have tools to fetch historical
data, live prices, technical indicators, a simple next-day price prediction, and a
rule-based buy/hold/sell suggestion.

Rules:
- Always use tools to get real data rather than guessing numbers.
- When giving a suggestion, briefly explain the reasoning behind it in plain language.
- Always end any buy/hold/sell suggestion with a short disclaimer that this is not
  financial advice and is based on limited historical data.
- If a tool returns an error, tell the user clearly instead of making up data.
"""


# ----------------------------------------------------------------------------
# Agent loop
# ----------------------------------------------------------------------------

def run_agent(user_message: str, max_turns: int = 5) -> str:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_message}
    ]

    for _ in range(max_turns):
        response = client.chat.completions.create(
            model=MODEL,
            max_tokens=1024,
            tools=TOOL_DEFINITIONS,
            messages=messages
        )

        choice = response.choices[0]
        msg = choice.message

        if not msg.tool_calls:
            # Final text answer
            return msg.content or ""

        # Append assistant's tool-call turn to the conversation
        messages.append({
            "role": "assistant",
            "content": msg.content,
            "tool_calls": msg.tool_calls
        })

        # Execute every tool call in this turn
        for tool_call in msg.tool_calls:
            func = TOOL_FUNCTIONS.get(tool_call.function.name)
            try:
                args = json.loads(tool_call.function.arguments)
            except json.JSONDecodeError:
                args = {}

            if func is None:
                result = {"error": f"Unknown tool: {tool_call.function.name}"}
            else:
                try:
                    result = func(**args)
                except Exception as e:
                    result = {"error": f"Tool execution failed: {str(e)}"}

            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "name": tool_call.function.name,
                "content": json.dumps(result)
            })

    return "Reached max turns without a final answer — try a simpler question."


# ----------------------------------------------------------------------------
# CLI entry point
# ----------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()
    print("Stock agent ready. Type a question (or 'quit' to exit).")
    while True:
        user_input = input("\nYou: ").strip()
        if user_input.lower() in ("quit", "exit"):
            break
        if not user_input:
            continue
        answer = run_agent(user_input)
        print(f"\nAgent: {answer}")